#!/usr/bin/env bash

xgettext --language=Python --keyword=_ --output=matemenu.pot \
usr/lib/ubuntu-mate/mateMenu/mateMenu.py \
usr/lib/ubuntu-mate/mateMenu/mateMenuConfig.py \
usr/lib/ubuntu-mate/mateMenu/keybinding.py \
usr/lib/ubuntu-mate/mateMenu/plugins/recent.py \
usr/lib/ubuntu-mate/mateMenu/plugins/applications.py \
usr/lib/ubuntu-mate/mateMenu/plugins/system_management.py \
usr/lib/ubuntu-mate/mateMenu/plugins/places.py
