#!/usr/bin/env bash

xgettext --language=Python --keyword=_ --output=mate-menu.pot \
usr/lib/ubuntu-mate/mate-menu/mate-menu.py \
usr/lib/ubuntu-mate/mate-menu/mate-menu-config.py \
usr/lib/ubuntu-mate/mate-menu/keybinding.py \
usr/lib/ubuntu-mate/mate-menu/plugins/recent.py \
usr/lib/ubuntu-mate/mate-menu/plugins/applications.py \
usr/lib/ubuntu-mate/mate-menu/plugins/system_management.py \
usr/lib/ubuntu-mate/mate-menu/plugins/places.py \
usr/lib/ubuntu-mate/common/mate-remove-application.py
