#!/usr/bin/env python3

# Copyright (C) 2007-2014 Clement Lefebvre <root@linuxmint.com>
# Copyright (C) 2015-2016 Martin Wimpress <code@ubuntu-mate.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.

import os
import shutil
import subprocess
import sys

if len(sys.argv) > 1:
    if (sys.argv[1] in ["help", "h", "-?", "--help", "-h", "?"]):
        print("MATE Menu - Advanced MATE Menu\n")
        print("options:")
        print(" [--]help, [-]h Display this help.")
        print(" [--]clean, [--]clear, [--]reset Restore settings to default.\n")
    elif (sys.argv[1] in ["clean", "clear", "reset",
          "--clean", "--clear", "--reset"]):
        configPath = os.environ.get("XDG_CONFIG_HOME",
                                    os.path.join(os.environ["HOME"], ".config"))

        for path in ("org.mate.mate-menu", "org.mate.mate-menu.plugins.places",
                     "org.mate.mate-menu.plugins.applications",
                     "org.mate.mate-menu.plugins.recent",
                     "org.mate.mate-menu.plugins.system_management"):
            subprocess.call(['gsettings', 'reset-recursively', path])

        config_files = os.path.join(configPath, 'mate-menu')
        if os.path.isdir(config_files):
            shutil.rmtree(config_files)

        print("All MATE Menu settings are now restored to default")
else:
    matemenu = os.path.join('/','usr','lib','mate-menu','mate-menu.py')
    subprocess.call([matemenu])
