#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (C) 2015 by Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.

import os
import subprocess
import sys

from glob import glob
from setuptools import setup
from setuptools.command.install import install

import DistUtilsExtra.command.build_extra
import DistUtilsExtra.command.build_i18n
import DistUtilsExtra.command.clean_i18n

# to update i18n .mo files (and merge .pot file into .po files) run on Linux:
#     tx pull -a
#     python setup.py build_i18n -m
#     tx push -s

# silence pyflakes, __VERSION__ is properly assigned below...
__VERSION__ = '0.0.0.0'
for line in open('lib/mate-menu.py').readlines():
    if (line.startswith('__VERSION__')):
        exec(line.strip())
        break

PROGRAM_VERSION = __VERSION__

def process_template(input_file, output_file, prefix):
    """Process a .in template file, substituting @PREFIX@ with the actual prefix."""
    with open(input_file, 'r') as f:
        content = f.read()
    content = content.replace('@PREFIX@', prefix)
    with open(output_file, 'w') as f:
        f.write(content)

def datafilelist(installbase, sourcebase):
    datafileList = []
    for root, subFolders, files in os.walk(sourcebase):
        fileList = []
        for f in files:
            fileList.append(os.path.join(root, f))
        datafileList.append((root.replace(sourcebase, installbase), fileList))
    return datafileList

data_files = [
    ("share/man/man1".format(prefix=sys.prefix), glob("data/*.1")),
    ("share/glib-2.0/schemas".format(prefix=sys.prefix),
        [
            "data/org.mate.mate-menu.gschema.xml"
        ] + glob("data/plugins/org.mate.mate-menu.plugins.*.gschema.xml"),
    ),
    ("share/mate-panel/applets".format(prefix=sys.prefix),
        [
            "data/org.mate.panel.MateMenuApplet.mate-panel-applet",
        ]
    ),
    ("share/dbus-1/services".format(prefix=sys.prefix),
        [
            "data/org.mate.panel.applet.MateMenuAppletFactory.service",
        ]
    ),
    ("share/mate-menu".format(prefix=sys.prefix),
        [
            "data/mate-menu.glade",
            "data/mate-menu-config.glade",
            "data/popup.xml",
            "data/applications.list",
        ]
    ),
    ("share/mate-menu/plugins".format(prefix=sys.prefix),
        [
            "data/plugins/applications.glade",
            "data/plugins/system_management.glade",
            "data/plugins/places.glade",
            "data/plugins/recent.glade",
        ]
    ),
    ("share/mate-menu/icons/search_engines".format(prefix=sys.prefix),
        [
            "data/icons/ddg.png",
            "data/icons/google.png",
            "data/icons/wikipedia.png",
        ]
    ),
    ("lib/mate-menu".format(prefix=sys.prefix), glob("lib/*.py*")),
]
data_files.extend(datafilelist("share/locale", 'build/mo'))

class InstallWithSchemas(install):
    """Custom install command that compiles GSettings schemas."""

    def get_runtime_prefix(self):
        """The prefix as it should appear at runtime.

        When installing into a staging area (--root, used for packaging), the
        root is not part of the runtime path, so strip it from the prefix.
        """
        prefix = self.prefix or sys.prefix
        if self.root and prefix.startswith(self.root):
            prefix = prefix[len(self.root):]
        return os.path.normpath(prefix)

    def write_prefix_module(self):
        """Record the actual install prefix for mate_menu.config."""
        prefix = self.get_runtime_prefix()
        target = os.path.join(self.install_lib, 'mate_menu', '_prefix.py')
        print(f"Writing {target} (PREFIX={prefix})")
        with open(target, 'w') as f:
            f.write('# Generated by setup.py install; do not edit.\n'
                    f'PREFIX = {prefix!r}\n')

    def process_templates(self, prefix):
        """Substitute @PREFIX@ in the applet and service template files.

        Runs in the install command so the real --prefix is known even when
        build and install are invoked as separate commands. Files are written
        to the source tree (gitignored) before install.run() copies them.
        """
        template_dir = 'data'
        templates = [
            ('org.mate.panel.MateMenuApplet.mate-panel-applet.in',
             'org.mate.panel.MateMenuApplet.mate-panel-applet'),
            ('org.mate.panel.applet.MateMenuAppletFactory.service.in',
             'org.mate.panel.applet.MateMenuAppletFactory.service'),
        ]

        for template_in, template_out in templates:
            input_file = os.path.join(template_dir, template_in)
            output_file = os.path.join(template_dir, template_out)
            if os.path.exists(input_file):
                print(f"Processing template: {input_file} -> {output_file} (prefix={prefix})")
                process_template(input_file, output_file, prefix)

    def run(self):
        # Process templates with the actual install prefix before the
        # standard install copies the generated files into place
        self.process_templates(self.get_runtime_prefix())

        # Run the standard install
        install.run(self)

        # Record the real install prefix so mate_menu.config can find its
        # data at runtime, regardless of where the interpreter lives
        self.write_prefix_module()

        # Compile GSettings schemas
        # Account for --root option (used for packaging)
        root = self.root or ''
        prefix = self.prefix or sys.prefix
        schema_dir = os.path.join(root, prefix.lstrip('/'), 'share', 'glib-2.0', 'schemas')
        if os.path.isdir(schema_dir):
            print(f"Compiling GSettings schemas in {schema_dir}...")
            try:
                subprocess.run(['glib-compile-schemas', schema_dir], check=True)
            except subprocess.CalledProcessError as e:
                print(f"Warning: Failed to compile schemas: {e}", file=sys.stderr)
            except FileNotFoundError:
                print("Warning: glib-compile-schemas not found", file=sys.stderr)

if sys.argv[1] == "build":
    import compileall
    compileall.compile_dir("lib")

cmdclass = {
    "build" : DistUtilsExtra.command.build_extra.build_extra,
    "build_i18n" :  DistUtilsExtra.command.build_i18n.build_i18n,
    "clean": DistUtilsExtra.command.clean_i18n.clean_i18n,
    "install": InstallWithSchemas,
}

setup(
    name = "mate-menu",
    version = PROGRAM_VERSION,
    description = "An advanced menu for MATE. Supports filtering, favorites, autosession, and many other features.",
    license = 'GPLv2+',
    author = 'Martin Wimpress',
    url = 'https://github.com/ubuntu-mate/mate-menu/',
    packages = [ 'mate_menu', 'mate_menu.plugins' ],
    # package_dir = {
    #     '': '.',
    # },
    data_files = data_files,
    install_requires = [ 'setuptools', 'configobj' ],
    scripts = [ 'mate-menu' ],
    cmdclass = cmdclass,
    zip_safe = True,
)
