#!/usr/bin/env bash

sudo rm -rf /usr/lib/ubuntu-mate/mateMenu
sudo rm -rf /usr/lib/ubuntu-mate/common
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas

python /usr/lib/ubuntu-mate/mateMenu/mateMenu.py
