.TH mate\-menu 1 "" ""
.SH NAME
mate-menu \- Advanced menu for the MATE desktop environment's panel
.SH SYNOPSIS
.B mate-menu \fR[option]
.SH DESCRIPTION
An advanced menu for MATE. Supports filtering, favorites, autosession,
and many other features.

.SH OPTIONS
.TP
.B [\-\-]help\fR,\fB [\-]h\fR,\fB [\-]?
Display command line options.
.TP
.B [\-\-]clean\fR,\fB [\-\-]clear\fR,\fB [\-\-]reset
Restore the MATE Menu settings to default by deleting the settings file (\fI~/.config/mate-menu/\fR).
